create table "public"."hobby_items" (
  "id" bigint generated by default as identity not null,
  "group_id" bigint not null,
  "title" text not null,
  "subtitle" text,
  "creator" text,
  "year" integer,
  "image_url" text not null,
  "external_url" text not null,
  "sort_order" integer not null default 0,
  "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
  "updated_at" timestamp with time zone not null default timezone('utc'::text, now())
);

alter table "public"."hobby_items" add constraint "hobby_items_pkey" primary key ("id");
alter table "public"."hobby_items" add constraint "hobby_items_group_id_external_url_key" unique ("group_id", "external_url");
alter table "public"."hobby_items" add constraint "hobby_items_group_id_fkey" foreign key ("group_id") references "public"."hobby_item_groups"("id") on delete cascade not valid;
alter table "public"."hobby_items" validate constraint "hobby_items_group_id_fkey";
create index "hobby_items_group_id_sort_order_idx" on "public"."hobby_items" using btree ("group_id", "sort_order");
alter table "public"."hobby_items" enable row level security;
