create table "public"."hobby_item_groups" (
  "id" bigint generated by default as identity not null,
  "hobby_slug" text not null,
  "slug" text not null,
  "title" text not null,
  "item_kind" text not null,
  "sort_order" integer not null default 0,
  "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
  "updated_at" timestamp with time zone not null default timezone('utc'::text, now())
);

alter table "public"."hobby_item_groups" add constraint "hobby_item_groups_pkey" primary key ("id");
alter table "public"."hobby_item_groups" add constraint "hobby_item_groups_hobby_slug_slug_key" unique ("hobby_slug", "slug");
alter table "public"."hobby_item_groups" add constraint "hobby_item_groups_item_kind_check" check ("item_kind" = any (array['film'::text, 'book'::text]));
create index "hobby_item_groups_hobby_slug_sort_order_idx" on "public"."hobby_item_groups" using btree ("hobby_slug", "sort_order");
alter table "public"."hobby_item_groups" enable row level security;
