-- groups
insert into public.hobby_item_groups (hobby_slug, slug, title, item_kind, sort_order) values
('films', 'gonna-watch-soon', 'gonna watch soon', 'film', 1),
('films', '2020-now', '2020 - now', 'film', 2),
('films', '2010-2019', '2010 - 2019', 'film', 3),
('films', '2000-2009', '2000 - 2009', 'film', 4),
('films', 'before-2000', 'before 2000', 'film', 5),
('reading', 'reading-now', 'reading now', 'book', 1),
('reading', 'non-fiction', 'non-fiction', 'book', 2),
('reading', 'fiction', 'fiction', 'book', 3)
on conflict (hobby_slug, slug) do update set title = excluded.title, item_kind = excluded.item_kind, sort_order = excluded.sort_order;

-- items
insert into public.hobby_items (group_id, title, subtitle, creator, year, image_url, external_url, sort_order) values
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = 'gonna-watch-soon'), 'The Guernsey Literary and Potato Peel Pie Society', '根西岛文学与土豆皮馅饼俱乐部', NULL, 2018, 'https://m.media-amazon.com/images/M/MV5BNjIyNzhhMmQtMjNlZS00MGRkLWE0ODgtY2E4MGMzMjk2M2IzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg', 'https://www.rottentomatoes.com/m/the_guernsey_literary_and_potato_peel_pie_society', 1),
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = 'gonna-watch-soon'), 'この世界の片隅に', '谢谢你，在世界角落中找到我 ', NULL, 2017, 'https://upload.wikimedia.org/wikipedia/zh/thumb/5/54/In_This_Corner_of_the_World_poster.jpeg/220px-In_This_Corner_of_the_World_poster.jpeg', 'https://www.rottentomatoes.com/m/in_this_corner_of_the_world', 2),
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = 'gonna-watch-soon'), 'Los versos del olivido', '遗忘诗行', NULL, 2017, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTDUcYHB0CeAq_MtYHKSy4upJ_gBK8-CBt7ce7mE-Qb_1TluI9', 'https://www.rottentomatoes.com/m/oblivion_verses', 3),
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = 'gonna-watch-soon'), 'The Bookshop', '书店', NULL, 2017, 'https://m.media-amazon.com/images/M/MV5BNDIzYjIyMGEtYzIyZS00OGY3LWI5ODYtN2M1YjAxOTA5OTgzXkEyXkFqcGdeQXVyMzI3MDEzMzM@._V1_FMjpg_UX1000_.jpg', 'https://www.rottentomatoes.com/m/the_bookshop', 4),
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = 'gonna-watch-soon'), 'Dans les forêts de Sibérie', '在西伯利亚森林中', NULL, 2016, 'https://m.media-amazon.com/images/M/MV5BZDY2MjE1NjYtNzFlYy00N2EyLWI2NGYtNzdlOWI1YWFmMjBkXkEyXkFqcGdeQXVyMjI0OTQ0MzI@._V1_FMjpg_UX1000_.jpg', 'https://www.rottentomatoes.com/m/in_the_forests_of_siberia', 5),
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = 'gonna-watch-soon'), 'リトル・フォレスト 冬・春', '小森林 冬春篇', NULL, 2015, 'https://static.iyf.tv/upload/video/201506281754285422517.jpg', 'https://www.rottentomatoes.com/m/little_forest_fuyu_haru', 6),
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = 'gonna-watch-soon'), 'リトル・フォレスト 夏・秋', '小森林 夏秋篇', NULL, 2014, 'https://picx.zhimg.com/v2-74f867e1e62b67a4a97c0c6059eb3414_720w.jpg?source=172ae18b', 'https://www.rottentomatoes.com/m/little_forest_summerautumn', 7),
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = 'gonna-watch-soon'), 'The Wind Will Carry Us', '随风而逝', NULL, 1999, 'https://resizing.flixster.com/Yfw-FY8QpOl4CFZHIDsPS4UIDHA=/206x305/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p25640_v_v8_af.jpg', 'https://www.rottentomatoes.com/m/the_wind_will_carry_us', 8)
on conflict (group_id, external_url) do update set title = excluded.title, subtitle = excluded.subtitle, creator = excluded.creator, year = excluded.year, image_url = excluded.image_url, sort_order = excluded.sort_order;

insert into public.hobby_items (group_id, title, subtitle, creator, year, image_url, external_url, sort_order) values
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = '2020-now'), 'Dune: Part 2', '沙丘2', NULL, 2024, 'https://m.media-amazon.com/images/I/51ZM+aTI7rL._AC_UF894,1000_QL80_.jpg', 'https://www.rottentomatoes.com/m/dune_part_two', 1),
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = '2020-now'), '天間荘の三姉妹', '天间庄的三姊妹', NULL, 2023, 'https://p2.bahamut.com.tw/HOME/creationCover/53/0005654853_B.JPG', 'https://www.rottentomatoes.com/m/three_sisters_of_tenmasou', 2),
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = '2020-now'), 'さかなのこ', '鱼之子', NULL, 2022, 'https://k.sinaimg.cn/n/spider20220713/745/w640h905/20220713/a39b-7a79366755f17b687cdfad8b7fbec9d9.jpg/w700d1q75cms.jpg?by=cms_fixed_width', 'https://www.rottentomatoes.com/m/the_fish_tale', 3),
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = '2020-now'), 'Poor Things', '可怜的东西', NULL, 2023, 'https://www.posterhub.com.sg/images/detailed/140/111966_Poor_Things_Final.jpg', 'https://www.rottentomatoes.com/m/poor_things', 4),
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = '2020-now'), 'Johnny Keep Walking!', '年会不能停！', NULL, 2023, 'https://resizing.flixster.com/ZRUsI6aMbYQZNqhRCsHgQKfThpc=/206x305/v2/https://resizing.flixster.com/DFRx-gh1zrLK18Ylrl4dWwCVQ7w=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzJkM2ZiNzNmLWMzZTctNDVlYy1iMzZjLWQ1ZGFkMjNhZjY5Yy5qcGc=', 'https://www.rottentomatoes.com/m/johnny_keep_walking', 5),
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = '2020-now'), '君たちはどう生きるか', 'The boy and the heron 你想活出怎样的人生', NULL, 2023, 'https://www.posterhub.com.sg/images/detailed/141/111988_The_Boy_and_the_Heron_Final.jpg', 'https://www.rottentomatoes.com/m/the_boy_and_the_heron', 6),
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = '2020-now'), 'After sun', '晒后假日', NULL, 2022, 'https://m.media-amazon.com/images/I/51rtaKI9mqL._AC_UF894,1000_QL80_.jpg', 'https://www.rottentomatoes.com/m/aftersun', 7),
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = '2020-now'), 'Dune', '沙丘', NULL, 2021, 'https://m.media-amazon.com/images/I/61CRq2R6i4L._AC_UF894,1000_QL80_.jpg', 'https://www.rottentomatoes.com/m/dune_2021', 8),
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = '2020-now'), 'CODA', 'CODA', NULL, 2021, 'https://resizing.flixster.com/SjEszAGGYlaasiZ_kJZhf5POWFg=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzdhMTUyZDA5LTlkMDktNGE0OC05ZjM3LThmZGQ3OTI1YTM4OS5wbmc=', 'https://www.rottentomatoes.com/m/coda_2021', 9),
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = '2020-now'), 'Belfast', '贝尔法斯特', NULL, 2021, 'https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p19677787_v_v13_ae.jpg', 'https://www.rottentomatoes.com/m/belfast', 10),
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = '2020-now'), '嫌われ松子の一生', 'Memories of Matsuko 被嫌弃的松子的一生', NULL, 2021, 'https://upload.wikimedia.org/wikipedia/zh/thumb/7/75/%E8%A2%AB%E5%AB%8C%E5%BC%83%E7%9A%84%E6%9D%BE%E5%AD%90%E7%9A%84%E4%B8%80%E7%94%9F.PNG/220px-%E8%A2%AB%E5%AB%8C%E5%BC%83%E7%9A%84%E6%9D%BE%E5%AD%90%E7%9A%84%E4%B8%80%E7%94%9F.PNG', 'https://www.rottentomatoes.com/m/memories_of_matsuko', 11),
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = '2020-now'), 'My Salinger Year', '我的塞林格之年', NULL, 2020, 'https://upload.wikimedia.org/wikipedia/en/3/3c/My_Salinger_Year.png', 'https://www.rottentomatoes.com/m/my_salinger_year', 12)
on conflict (group_id, external_url) do update set title = excluded.title, subtitle = excluded.subtitle, creator = excluded.creator, year = excluded.year, image_url = excluded.image_url, sort_order = excluded.sort_order;

insert into public.hobby_items (group_id, title, subtitle, creator, year, image_url, external_url, sort_order) values
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = '2010-2019'), 'A rainy day in New York', '一个纽约的雨天', NULL, 2019, 'https://resizing.flixster.com/XeI_UoXJO7gea-NFLPJtbSS7k5o=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2QzZDU5ZjIzLTBjY2EtNGQzZi04ZDIwLTVlMzk5MGE4ODNjMC53ZWJw', 'https://www.rottentomatoes.com/m/a_rainy_day_in_new_york', 1),
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = '2010-2019'), 'Three Billboards Outside Ebbing, Missouri', '三块广告牌', NULL, 2017, 'https://www.posterhub.com.sg/images/detailed/89/three_billboards_outside_ebbing_missouri_final.jpg', 'https://www.rottentomatoes.com/m/three_billboards_outside_ebbing_missouri', 2),
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = '2010-2019'), 'Dunkirk', '敦刻尔克', NULL, 2017, 'https://resizing.flixster.com/6E4muZUNOKQHsbvu2FmQm-H3thg=/206x305/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p3829_p_v8_ab.jpg', 'https://www.rottentomatoes.com/m/dunkirk', 3),
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = '2010-2019'), '思い出のマーニー', 'When Marnie Was There 回忆中的玛尼', NULL, 2014, 'https://resizing.flixster.com/ZNtawuwnjrOshpc_2vp5ltzQSFM=/206x305/v2/https://resizing.flixster.com/5ljZmB7n__vlOL3hAtwX9kLcm48=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzExZmIxZjFlLTM1YTctNDM5ZS04ZGNlLTc4YjkyYzkxMWFlNC5qcGc=', 'https://www.rottentomatoes.com/m/when_marnie_was_there', 4),
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = '2010-2019'), 'Interstellar', '星际穿越', NULL, 2014, 'https://www.posterhub.com.sg/images/detailed/140/Interstellar_Final.jpg', 'https://www.rottentomatoes.com/m/interstellar', 5),
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = '2010-2019'), '風立ちぬ', 'The Wind Rises 起风了', NULL, 2013, 'https://resizing.flixster.com/BIv63SDuyUSkjO315qdfrFwb1CQ=/206x305/v2/https://resizing.flixster.com/rdaE-2g8ozNdGIwG8-zcgtRClsk=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2Y2ZWFiZTkzLTIzOGUtNGIwNC1iNGZmLWNjMGE1NGUwYzcwZS5qcGc=', 'https://www.rottentomatoes.com/m/the_wind_rises', 6),
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = '2010-2019'), '横道世之介', 'A Story of Yonosuke 横道世之介', NULL, 2013, 'https://resizing.flixster.com/yfTLNcHEWe6OKcisSnWXqA--U_A=/206x305/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p10390185_v_v8_aa.jpg', 'https://www.rottentomatoes.com/m/yokomichi_yonosuke', 7),
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = '2010-2019'), 'かぐや姫の物語', 'The Tale of the Princess Kaguya 辉夜姬物语', NULL, 2013, 'https://resizing.flixster.com/-VCkHPBuCfqfQK3obqH_FlaWMyY=/206x305/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p10922577_p_v8_aa.jpg', 'https://www.rottentomatoes.com/m/the_tale_of_the_princess_kaguya', 8),
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = '2010-2019'), 'コクリコ坂から', 'From Up on Poppy Hill 虞美人盛开的山坡', NULL, 2011, 'https://resizing.flixster.com/nJPemSgHcYTZsPN0VDyYcSNeRsY=/206x305/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p8822358_p_v8_aa.jpg', 'https://www.rottentomatoes.com/m/from_up_on_poppy_hill', 9),
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = '2010-2019'), '借りぐらしのアリエッティ', 'The Secret World of Arrietty 借东西的小人阿莉埃蒂', NULL, 2010, 'https://www.posterhub.com.sg/images/detailed/117/19_1A_1B.jpg', 'https://www.rottentomatoes.com/m/the_secret_world_of_arrietty', 10)
on conflict (group_id, external_url) do update set title = excluded.title, subtitle = excluded.subtitle, creator = excluded.creator, year = excluded.year, image_url = excluded.image_url, sort_order = excluded.sort_order;

insert into public.hobby_items (group_id, title, subtitle, creator, year, image_url, external_url, sort_order) values
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = '2000-2009'), '崖の上のポニョ', 'Ponyo 崖上的波妞', NULL, 2008, 'https://www.posterhub.com.sg/images/detailed/117/13_1A_1B_wql0-zy.jpg', 'https://www.rottentomatoes.com/m/ponyo', 1),
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = '2000-2009'), 'ハウルの動く城', 'Howl''s Moving Castle 哈尔的移动城堡', NULL, 2004, 'https://www.posterhub.com.sg/images/detailed/117/07_1A_1B_4mxo-zn.jpg', 'https://www.rottentomatoes.com/m/howls_moving_castle', 2),
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = '2000-2009'), '猫の恩返し', 'The Cat Returns 猫的报恩', NULL, 2002, 'https://resizing.flixster.com/NJ8BVMMqrzOJJLEoO67nabuX69s=/206x305/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p8985898_p_v8_ac.jpg', 'https://www.rottentomatoes.com/m/the_cat_returns', 3),
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = '2000-2009'), '千と千尋の神隠し', 'Spirited Away 千与千寻', NULL, 2001, 'https://www.posterhub.com.sg/images/detailed/5/away2.jpg', 'https://www.rottentomatoes.com/m/spirited_away', 4)
on conflict (group_id, external_url) do update set title = excluded.title, subtitle = excluded.subtitle, creator = excluded.creator, year = excluded.year, image_url = excluded.image_url, sort_order = excluded.sort_order;

insert into public.hobby_items (group_id, title, subtitle, creator, year, image_url, external_url, sort_order) values
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = 'before-2000'), 'もののけ姫', 'Princess Mononoke 幽灵公主', NULL, 1997, 'https://resizing.flixster.com/azielo2WZR5AOInD3HbvYrdrY8E=/206x305/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p23052_p_v8_ae.jpg', 'https://www.rottentomatoes.com/m/princess_mononoke', 1),
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = 'before-2000'), '情书', 'Love Letter 情书', NULL, 1995, 'https://resizing.flixster.com/a4KYdkEoSp7y0Lytx3DNp7HFquw=/206x305/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p22066_v_v8_ac.jpg', 'https://www.rottentomatoes.com/m/10001359-love_letter', 2),
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = 'before-2000'), '耳をすませば', 'Whisper of the Heart 侧耳倾听', NULL, 1995, 'https://m.media-amazon.com/images/M/MV5BZDg0MWNmNjktMGEwZC00ZDlmLWI1MTUtMDBmNjQzMWM2NjBjXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg', 'https://www.rottentomatoes.com/m/whisper_of_the_heart', 3),
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = 'before-2000'), 'Il Postino', '邮差', NULL, 1994, 'https://m.media-amazon.com/images/M/MV5BZmVhNWIzOTMtYmVlZC00ZDVmLWIyODEtODEzOTAxYjAwMzVlXkEyXkFqcGdeQXVyMzIwNDY4NDI@._V1_FMjpg_UX1000_.jpg', 'https://www.rottentomatoes.com/m/il_postino', 4),
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = 'before-2000'), 'Schindler''s List', '辛德勒的名单', NULL, 1993, 'https://resizing.flixster.com/T0OfKJgU0a1nllJbS1RV3cPL9QY=/206x305/v2/https://resizing.flixster.com/P3NTptLJcIlWlLQwZMTWcITYaoY=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzlmMTBiZGYxLTFjZTctNGZiZS05OGU4LTAxNGIzNGZmNTVlMy5qcGc=', 'https://www.rottentomatoes.com/m/schindlers_list', 5),
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = 'before-2000'), '紅の豚', 'Porco Rosso 红猪', NULL, 1992, 'https://m.media-amazon.com/images/M/MV5BNTZjMDc2N2UtZTdjZi00ODljLTgyZmEtNDljZDAwODY4NDVhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg', 'https://www.rottentomatoes.com/m/porco_rosso', 6),
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = 'before-2000'), 'おもひでぽろぽろ', 'Only Yesterday 岁月的童话', NULL, 1991, 'https://resizing.flixster.com/egYV6w2fiQp2Qdsgzt8hI9GM4SQ=/206x305/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p160150_p_v8_ab.jpg', 'https://www.rottentomatoes.com/m/only_yesterday', 7),
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = 'before-2000'), '魔女の宅急便', 'Kiki''s Delivery Service 魔女宅急便', NULL, 1989, 'https://resizing.flixster.com/cRVV0GRX4YvLjwJb8E0kcYHBSCY=/206x305/v2/https://resizing.flixster.com/ww1xQD57II223RFmcO7oVLI2ahQ=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzI4ZDY2MTllLWQ5MzktNDVlNC04MWQ4LWVmODQ4ODZiYTRkMS53ZWJw', 'https://www.rottentomatoes.com/m/kikis_delivery_service', 8),
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = 'before-2000'), 'となりのトトロ', 'My Neighbor Totoro 龙猫', NULL, 1988, 'https://www.posterhub.com.sg/images/detailed/5/totoro.jpg', 'https://www.rottentomatoes.com/m/my_neighbor_totoro', 9),
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = 'before-2000'), '火垂るの墓', 'Grave of the Fireflies 萤火虫之墓', NULL, 1988, 'https://resizing.flixster.com/BFNmx3r2Yoe0AFfg-HjBNdJ_cPs=/206x305/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p158931_p_v8_aa.jpg', 'https://www.rottentomatoes.com/m/grave_of_the_fireflies', 10),
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = 'before-2000'), '風の谷のナウシカ', 'Nausicaä of the Valley of the Wind 风之谷', NULL, 1984, 'https://resizing.flixster.com/60bLBe-JzVJHbV8RPZg5PZXeT9w=/206x305/v2/https://resizing.flixster.com/zVDN9-WduG1ZlDCpGzaQhtqr8lg=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2IzMmE5NTliLTRmYjctNGI2Yy1iOWI2LWJlZGY2ZWM4ZWEyNy5qcGc=', 'https://www.rottentomatoes.com/m/nausicaa_of_the_valley_of_the_wind', 11),
((select id from public.hobby_item_groups where hobby_slug = 'films' and slug = 'before-2000'), '天空の城ラピュタ', 'Laputa: Castle in the Sky 天空之城', NULL, 1986, 'https://www.posterhub.com.sg/images/detailed/141/Castle_in_the_Sky_China_l242-g6.jpg', 'https://www.rottentomatoes.com/m/castle_in_the_sky', 12)
on conflict (group_id, external_url) do update set title = excluded.title, subtitle = excluded.subtitle, creator = excluded.creator, year = excluded.year, image_url = excluded.image_url, sort_order = excluded.sort_order;

insert into public.hobby_items (group_id, title, subtitle, creator, year, image_url, external_url, sort_order) values
((select id from public.hobby_item_groups where hobby_slug = 'reading' and slug = 'reading-now'), 'Atomic Habits', NULL, 'James Clear', NULL, 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1655988385i/40121378.jpg', 'https://www.goodreads.com/book/show/40121378-atomic-habits?from_search=true&from_srp=true&qid=x9fCTrFR9g&rank=1', 1)
on conflict (group_id, external_url) do update set title = excluded.title, subtitle = excluded.subtitle, creator = excluded.creator, year = excluded.year, image_url = excluded.image_url, sort_order = excluded.sort_order;

insert into public.hobby_items (group_id, title, subtitle, creator, year, image_url, external_url, sort_order) values
((select id from public.hobby_item_groups where hobby_slug = 'reading' and slug = 'non-fiction'), '被讨厌的勇气', NULL, '岸见一郎', NULL, 'https://images.weserv.nl/?url=https://img9.doubanio.com/view/subject/m/public/s34348664.jpg', 'https://book.douban.com/subject/36150914/', 1)
on conflict (group_id, external_url) do update set title = excluded.title, subtitle = excluded.subtitle, creator = excluded.creator, year = excluded.year, image_url = excluded.image_url, sort_order = excluded.sort_order;

insert into public.hobby_items (group_id, title, subtitle, creator, year, image_url, external_url, sort_order) values
((select id from public.hobby_item_groups where hobby_slug = 'reading' and slug = 'fiction'), '镰仓旋涡咨询所', NULL, '青山美智子', NULL, 'https://images.weserv.nl/?url=https://img1.doubanio.com/view/subject/s/public/s34278638.jpg', 'https://book.douban.com/subject/36014224/', 1),
((select id from public.hobby_item_groups where hobby_slug = 'reading' and slug = 'fiction'), '公园生活', NULL, '吉田修一', NULL, 'https://images.weserv.nl/?url=https://img3.doubanio.com/view/subject/s/public/s27226813.jpg', 'https://book.douban.com/subject/25835239/', 2),
((select id from public.hobby_item_groups where hobby_slug = 'reading' and slug = 'fiction'), '克拉拉与太阳', NULL, '石黑一雄', NULL, 'https://images.weserv.nl/?url=https://img9.doubanio.com/view/subject/s/public/s33821754.jpg', 'https://book.douban.com/subject/35315153/', 3),
((select id from public.hobby_item_groups where hobby_slug = 'reading' and slug = 'fiction'), '岛上书店', NULL, '加布瑞埃拉·泽文', NULL, 'https://images.weserv.nl/?url=https://img1.doubanio.com/view/subject/s/public/s29810488.jpg', 'https://book.douban.com/subject/26340138/', 4),
((select id from public.hobby_item_groups where hobby_slug = 'reading' and slug = 'fiction'), '我不能放下的一切', NULL, '丁丁张', NULL, 'https://images.weserv.nl/?url=https://img1.doubanio.com/view/subject/s/public/s34375378.jpg', 'https://book.douban.com/subject/36153728/', 5),
((select id from public.hobby_item_groups where hobby_slug = 'reading' and slug = 'fiction'), '长安的荔枝', NULL, '马伯庸', NULL, 'https://images.weserv.nl/?url=https://img3.doubanio.com/view/subject/s/public/s34327482.jpg', 'https://book.douban.com/subject/36104107/', 6)
on conflict (group_id, external_url) do update set title = excluded.title, subtitle = excluded.subtitle, creator = excluded.creator, year = excluded.year, image_url = excluded.image_url, sort_order = excluded.sort_order;


-- ratings 
insert into public.ratings (id, positive_rating, negative_rating, comment) values ('dune_2021', 120, 5, 'Seeded rating for Dune'), ('spirited_away', 300, 10, 'Classic — seeded') on conflict (id) do update set positive_rating = excluded.positive_rating, negative_rating = excluded.negative_rating, comment = excluded.comment;

-- bgms 
insert into public.bgms (id, title, artist, external_url) values ('bgm-ponyo', 'Ponyo Theme', 'Joe Hisaishi', 'https://example.com/ponyo'), ('bgm-one-summer-day', 'One Summer''s Day', 'Joe Hisaishi', 'https://example.com/one-summers-day') on conflict (id) do update set title = excluded.title, artist = excluded.artist, external_url = excluded.external_url;

-- post views 
insert into public.post_views (slug, view) values ('welcome', 42), ('about', 7) on conflict (slug) do update set view = excluded.view;