// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type Options = Collections['options']['schema']['_output']
export declare const options: Options

export type Tag = Collections['tags']['schema']['_output']
export declare const tags: Tag[]

export type Page = Collections['pages']['schema']['_output']
export declare const pages: Page[]

export type Post = Collections['posts']['schema']['_output']
export declare const posts: Post[]

export type Focus = Collections['focus']['schema']['_output']
export declare const focus: Focus[]

export type Hobbies = Collections['hobbies']['schema']['_output']
export declare const hobbies: Hobbies[]
