create table if not exists "public"."hobby_item_groups" (
  "id" bigint generated by default as identity not null,
  "hobby_slug" text not null,
  "slug" text not null,
  "title" text not null,
  "item_kind" text not null,
  "sort_order" integer not null default 0,
  "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
  "updated_at" timestamp with time zone not null default timezone('utc'::text, now()),
  constraint "hobby_item_groups_pkey" primary key ("id"),
  constraint "hobby_item_groups_hobby_slug_slug_key" unique ("hobby_slug", "slug"),
  constraint "hobby_item_groups_item_kind_check" check ("item_kind" = any (array['film'::text, 'book'::text]))
);

create index if not exists "hobby_item_groups_hobby_slug_sort_order_idx"
  on "public"."hobby_item_groups" using btree ("hobby_slug", "sort_order");

alter table "public"."hobby_item_groups" enable row level security;

create table if not exists "public"."hobby_items" (
  "id" bigint generated by default as identity not null,
  "group_id" bigint not null,
  "title" text not null,
  "subtitle" text,
  "creator" text,
  "year" integer,
  "image_url" text not null,
  "external_url" text not null,
  "sort_order" integer not null default 0,
  "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
  "updated_at" timestamp with time zone not null default timezone('utc'::text, now()),
  constraint "hobby_items_pkey" primary key ("id"),
  constraint "hobby_items_group_id_external_url_key" unique ("group_id", "external_url"),
  constraint "hobby_items_group_id_fkey" foreign key ("group_id") references "public"."hobby_item_groups"("id") on delete cascade
);

create index if not exists "hobby_items_group_id_sort_order_idx"
  on "public"."hobby_items" using btree ("group_id", "sort_order");

alter table "public"."hobby_items" enable row level security;
